### ISSUE TITLE
List of subreddits used to learn BioReddit embeddings

### ISSUE THREAD

**Issue by sopankhosla** [basaldella/bioreddit#1]
Could you please share the list of 68 Subreddits that were used to learn BioReddit embeddings?

**Comment by basaldella** [comment]
The list will be shared soon in a subsequent paper based on the same dataset - unfortunately, right now I can't share more information with you in order not to break the double-blind peer review. 

I'm leaving the issue open. I'll update and close it with when we will be able to share the full list.

**Comment by sap218** [comment]
Is this list available? :)

**Comment by basaldella** [comment]
Sure, you can find it here: https://arxiv.org/pdf/2010.03295.pdf . It's Table 6 in the Appendix.

Closing the issue
